### ISSUE TITLE
sbt dependencyTree task instead of dependency-tree 

### ISSUE THREAD

**Issue by cpapazaf** [snyk/snyk-sbt-plugin#7] opened 2017-12-07 13:01 UTC
### Expected behaviour
dependencyTree is the prefered sbt task for sbt-dependency-graph

### Actual behaviour
`addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.8.2")` is not any more available
```
[warn]  module not found: net.virtual-void#sbt-dependency-graph;0.8.2
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/net.virtual-void/sbt-dependency-graph/scala_2.12/sbt_1.0//0.8.2/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/net.virtual-void/sbt-dependency-graph/scala_2.12/sbt_1.0//0.8.2/ivys/ivy.xml
``` 

due to that, we cannot invoke `dependency-tree` anymore

### Steps to reproduce
install `addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.8.2")`

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by odinn1984** [comment] 2018-01-10 17:41
Hi!

so we solved it with adding an alias for dep tree…

```
echo “addSbtPlugin(\“net.virtual-void\” % \“sbt-dependency-graph\” % \“0.9.0\“)” >> /home/node/.sbt/1.0/plugins/plugins.sbt
echo “addCommandAlias(\“dependency-tree\“, \“dependencyTree\“)” >> /home/node/.sbt/1.0/user.sbt
```

and that way it works with the sbt plugin
that’s how we solved it in the image that we use docker with

**Comment by darscan** [comment] 2018-01-23 11:20
Hi @cpapazaf . Sorry for the delay in getting back to you. I've been unable to reproduce the issue locally. I tried with `sbt-dependency-graph` `0.8.2` and `0.9.0` both with `dependency-tree` and `dependencyTree` and all produce the expected results. What is the combination that fails? A PR has been raised here: https://github.com/snyk/snyk-sbt-plugin/pull/8 and I like to manually verify/understand.

**Comment by darscan** [comment] 2018-01-23 17:31
Fixed by https://github.com/snyk/snyk-sbt-plugin/pull/8

**Closed by darscan** 2018-01-23 17:31 UTC
